### ISSUE TITLE
Frequency adjustment precision and frequency to note conversion accuracy

### ISSUE THREAD

**Issue by elcalenx** [iurienistor/geonkick#176]
Here's a couple of minor things that have been bugging me related to adjusting frequency graph nodes. First of all, the precision in the low end seems a little lacking, when the frequency range is high. Like, when I've got the frequency knob maxed out, I can't seem to adjust a node to 43 Hz, it always jumps from 42 to 44... It would be really nice if there was a way to do finer adjustments, or even manually enter values for nodes...

Secondly, I noticed some weird behaviour with the note name display for frequency nodes. I set a node to 44 Hz, and it read as F1. But after saving and reloading the project it now reads as F#1... Some rounding issue going on or something? (If F1 is considered to be 43.65 Hz and F#1 is 46.25 Hz, then 44 should round to F1, right? Well, anything up to 44.95 anyway, if my math isn't way off...)

**Comment by iurienistor** [comment]
Yes, I'll think how to add this, so the user be able to input a more exact frequency.

The second issue, please, check this fixed issue where it should fix the conversion from frequency to note - https://github.com/free-sm/geonkick/issues/180
