### ISSUE TITLE
Export dialog should remember file name and format setting

### ISSUE THREAD

**Issue by SpotlightKid** [iurienistor/geonkick#32]
The export dialog, when opened again after having already exported the current sound once, has the filename field blank, and the file format and mono/stereo settings seems to always reset to "WAV 16" / "Mono". It would be very helpful if these to settings could be remembered.

The export directory path ("Location") is already remembered, which is nice.

Test with version 1.6 (standalone and LV2) on [Manjaro Linux](https://gist.github.com/SpotlightKid/9fbee0dbb54aa82ffdd15bf90c3b86b3).

**Comment by iurienistor** [comment]
Hi! Thank you, scheduled for 1.8.

**Comment by iurienistor** [comment]
Implemented. It is only per session, if the applications is closed than the info is lost. For LV2 the info is lost only if the DAW is closed. Later I'll implemented a more persistent settings.
