### ISSUE TITLE
FR: open / save / export file and directory selection dialog improvements

### ISSUE THREAD

**Issue by SpotlightKid** [iurienistor/geonkick#37]
* When (double?) clicking file in entry list, copy name to file name text entry.
* When no previous directory has been set for "Open" function yet, use the previous directory of "Save" function.
* Add button to add new directory in current directory.
* Ask for confirmation before overwriting existing file.

**Comment by iurienistor** [comment]
This file dialog actually will be moved and improved in Redkite as RkFileDialog. Thus, I plan this modifications later, probably for Geonkick version 2.0.
